publish_to: "none"

name: nocsis_classroom

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.5.4
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  cloud_functions: ^4.5.8
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  collection: ^1.18.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/weather/
