targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - swagger/api.json
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: swagger/
          output_folder: lib/generated/api_client/
          separate_models: true
