publish_to: "none"

name: nocsis_personal

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  firebase_core: ^2.4.1
  firebase_auth: ^4.2.2
  cloud_functions: ^4.0.7
  go_router: ^13.0.1
  go_router_prototype: ^0.1.0
  freezed: ^2.0.3
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  intl: ^0.19.0
  collection: ^1.16.0
  animations: ^2.0.2
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/Icon-192.png
