name: nocsis_personal
description: Nocsis Personal

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  firebase_core: ^2.4.1
  firebase_auth: ^4.2.2
  cloud_functions: ^4.0.7
  go_router: ^12.1.3
  go_router_prototype: ^0.1.0
  flutter_riverpod: ^2.1.3
  freezed: ^2.0.3
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  intl: ^0.18.0
  collection: ^1.16.0
  animations: ^2.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Icon-192.png
