name: Deploy Frontend

on:
    workflow_call:
        inputs:
            environment:
                description: "Deployment environment"
                required: true
                type: string
            channel_id:
                description: "Firebase Hosting channel ID"
                required: true
                type: string
        secrets:
            DEPLOY_FIREBASE_HOSTING_SERVICE_ACCOUNT:
                required: true

permissions: {}

jobs:
    deploy:
        environment:
            name: ${{ inputs.environment }}
        permissions:
            checks: write
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - name: Setup Tools
              uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
            - name: Install dependencies
              working-directory: ./frontend
              run: flutter pub get --enforce-lockfile
            - name: Generate OpenAPI spec
              working-directory: ./backend
              run: pnpm install --frozen-lockfile && pnpm run generate-openapi
            - name: Run build_runner
              working-directory: ./frontend
              run: flutter pub run build_runner build
            - name: Build
              working-directory: ./frontend
              run: flutter build web --wasm
            - name: Deploy
              uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c # v0.10.0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.DEPLOY_FIREBASE_HOSTING_SERVICE_ACCOUNT }}
                  channelId: ${{ inputs.channel_id }}
