name: Cleanup Preview

on:
  pull_request:
    types: [closed]

permissions: {}

jobs:
  cleanup:
    if: ${{ contains(github.event.pull_request.labels.*.name, '👀 Enable Preview') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: Preview
    env:
      CHANNEL_ID: pr-${{ github.event.pull_request.number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-action/providers/deploy-nocsis
          service_account: gh-actions-deploy@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
      - name: Delete Cloud Run tag
        run: |
          gcloud run services update-traffic backend \
            --remove-tags ${{ env.CHANNEL_ID }} \
            --project ${{ vars.GCP_PROJECT_ID }} \
            --region asia-northeast1
      - name: Setup Tools
        uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Delete Firebase Hosting channel
        run: pnpm firebase hosting:channel:delete ${{ env.CHANNEL_ID }} --project ${{ vars.GCP_PROJECT_ID }} --force
