name: Create Release Pull Request

on:
  push:
    branches: [development]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get_pr_number:
    outputs:
      release_pr_number: ${{ steps.get_pr_number.outputs.release_pr_number }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Existing Release PR
        id: get_pr_number
        run: |
          existing_release_pr_number=$(gh pr list -B main -H development --json "number" -q ".[0].number")
          if [ -n "$existing_release_pr_number" ]; then
            echo "release_pr_number=$existing_release_pr_number" >> $GITHUB_OUTPUT
          else
            release_pr_number=$(gh pr create -H development -B main -t "Release" -b "wip" | sed -n 's/.*\///p')
            echo "release_pr_number=$release_pr_number" >> $GITHUB_OUTPUT
          fi

  get_pr_content:
    needs: [get_pr_number]

    outputs:
      title: ${{ steps.make_title.outputs.title }}
      body: ${{ steps.make_body.outputs.body }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make Title
        id: make_title
        run: |
          title=$(echo "Release $(TZ=Asia/Tokyo date +'%Y-%m-%d')")
          echo "title=$title" >> $GITHUB_OUTPUT
      - name: Make Body
        id: make_body
        run: |
          release_pr_commits=$(gh pr view ${{ needs.get_pr_number.outputs.release_pr_number }} --json "commits" --jq "[.commits[].oid]")
          prs=$(gh pr list -B development -S "is:merged sort:created-asc" --json 'number,author,mergeCommit' | jq --argjson release_pr_commits "$release_pr_commits" '.[] | select(.mergeCommit.oid | IN($release_pr_commits[]))')
          body=$(echo "$prs" | jq -r '["- #\(.number) @\(.author.login)"] | join("\n")')
          body="${body//$'\n'/\\n}"
          echo "body=$body" >> $GITHUB_OUTPUT

  edit:
    needs: [get_pr_number, get_pr_content]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Release PR
        run: |
          body="${{ needs.get_pr_content.outputs.body }}"
          body=${body//\\n/$'\n'}
          gh pr edit ${{ needs.get_pr_number.outputs.release_pr_number }} -t "${{ needs.get_pr_content.outputs.title }}" -b "$body"
