name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: {}

concurrency:
  group: Deploy to Production
  cancel-in-progress: false

jobs:
  build_backend:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/_build_backend.yml
    with:
      persist: true

  build_functions:
    permissions:
      contents: read
    uses: ./.github/workflows/_build_functions.yml
    with:
      persist: true

  build_frontend:
    permissions:
      contents: read
    uses: ./.github/workflows/_build_frontend.yml
    with:
      persist: true

  deploy_backend:
    needs: [build_backend]
    permissions:
      id-token: write
    uses: ./.github/workflows/_deploy_backend.yml
    with:
      environment: Production
      image: ${{ needs.build_backend.outputs.image }}
      promote: true

  deploy_functions:
    needs: [build_functions]
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/_deploy_functions.yml
    with:
      environment: Production

  deploy_frontend:
    needs: [build_frontend, deploy_backend, deploy_functions]
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: ./.github/workflows/_deploy_frontend.yml
    with:
      environment: Production
      channel_id: live
