name: Deploy to Staging

on:
  push:
    branches: [update-deploy]
  workflow_dispatch:

concurrency:
  group: Deploy to Staging
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      env: Preview
    secrets: inherit
