name: Deploy to Staging

on:
  workflow_dispatch:

permissions: {}

concurrency:
  group: Deploy to Staging
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
      checks: write
    uses: ./.github/workflows/deploy.yml
    with:
      env: Preview
      channelId: stg
    secrets: inherit
