name: Deploy to Staging

on:
  workflow_dispatch:

concurrency:
  group: Deploy to Staging
  cancel-in-progress: true

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml

  deploy_frontend:
    needs: [prepare]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ needs.prepare.outputs.flutter_channel }}
          flutter-version: ${{ needs.prepare.outputs.flutter_version }}
          cache: true
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ needs.prepare.outputs.node_version }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: ./functions/package.json
      - name: Build
        run: flutter build web --wasm
      - name: Deploy
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./frontend
      - name: Set alias
        run: pnpm dlx vercel alias ${{ steps.deploy.outputs.preview-url }} stg.nocsis.app --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }}
