name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:
    inputs:
      channel_id:
        description: "Firebase Hosting channel ID"
        required: false
        default: preview

permissions: {}

concurrency:
  group: Deploy Preview ${{ github.event.pull_request.number || inputs.channel_id }}
  cancel-in-progress: true

jobs:
  build_backend:
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, '👀 Enable Preview') }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/_build_backend.yml
    with:
      persist: true

  build_frontend:
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, '👀 Enable Preview') }}
    permissions:
      contents: read
    uses: ./.github/workflows/_build_frontend.yml
    with:
      persist: true

  deploy_backend:
    needs: [build_backend]
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, '👀 Enable Preview') }}
    permissions:
      id-token: write
    uses: ./.github/workflows/_deploy_backend.yml
    with:
      environment: Preview
      image: ${{ needs.build_backend.outputs.image }}
      tag: ${{ github.event_name == 'workflow_dispatch' && inputs.channel_id || format('pr-{0}', github.event.pull_request.number) }}

  deploy_frontend:
    needs: [build_frontend, deploy_backend]
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, '👀 Enable Preview') }}
    permissions:
      checks: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/_deploy_frontend.yml
    with:
      environment: Preview
      channel_id: ${{ github.event_name == 'workflow_dispatch' && inputs.channel_id || format('pr-{0}', github.event.pull_request.number) }}
    secrets: inherit
