name: Deploy to Staging

on:
  workflow_dispatch:

concurrency:
  group: Deploy to Staging
  cancel-in-progress: true

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Tools
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Set token
        run: FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN_DEPLOY_FUNCTIONS }}
      - name: Deploy
        run: pnpm firebase deploy --only functions

  deploy_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Tools
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Build
        run: flutter build web --wasm
      - name: Deploy
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./frontend
      - name: Set alias
        run: pnpm dlx vercel alias ${{ steps.deploy.outputs.preview-url }} stg.nocsis.app --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }}
