name: Lint

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}_${{ github.ref }}
  cancel-in-progress: true

jobs:
  functions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Tools
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Type Check
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Tools
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Type Check
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Tools
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
      - name: Install dependencies
        run: flutter pub get --enforce-lockfile
      - name: Generate OpenAPI spec
        run: pnpm install --frozen-lockfile && pnpm run generate-openapi
        working-directory: ./backend
      - name: Run build_runner
        run: flutter pub run build_runner build
      - name: Lint
        run: flutter analyze
